# Generated by Django 4.1.7 on 2023-02-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_remove_cart_price_remove_cart_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='menuitem_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_details', to='LittleLemonAPI.menuitem'),
            preserve_default=False,
        ),
    ]
